import React from 'react';

import css from './randomFact.module.css';

function RandomFact() {
  return (
    <div id={css.randomFact}>
      <h4 id={css.factHeader}>Whisky Fact:</h4>
      <p id={css.factText}>
        generated by the API lorem ipsum dolores est lorem ipsum dolores est
        lorem ipsum dolores est lorem ipsum
      </p>
    </div>
  );
}

export default RandomFact;
